server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sinergy}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysqlroot}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service